name: release
on:
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'

# on:
#   release:
#     types: [published]

env:
  GCP_PROJECT_ID: simple-326714
  GCP_CLUSTER_NAME: simple-cluster
  GCP_CLUSTER_ZONE: europe-west1-b
  GCP_REGISTRY: europe-west3-docker.pkg.dev
  APP_NAME: next-app
  VERSION: 0.0.0 # ${{ github.event.release.tag_name }}

jobs:
  vars: 
    runs-on: ubuntu-latest
    outputs:
      HELM_IMAGE_TAG: ${{ steps.helm.outputs.HELM_IMAGE_TAG }}
    steps:
      - id: helm
        run: echo "::set-output name=HELM_IMAGE_TAG::${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/helm/${{ env.APP_NAME }}:${{ env.VERSION }}"
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Dump GitHub context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: echo "$GITHUB_CONTEXT"

  #     - name: build docker image
  #       run: docker build --tag ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/docker/${{ env.APP_NAME }}:${{ github.event.release.tag_name }} .

  #     - name: Set up gcloud
  #       uses: google-github-actions/setup-gcloud@master
  #       with:
  #         project_id: ${{ env.GCP_PROJECT_ID }}
  #         service_account_key: ${{ secrets.GCP_SA_KEY }}
  #         export_default_credentials: true
      
  #     - name: configure docker
  #       run: gcloud auth configure-docker ${{ env.GCP_REGISTRY }}

  #     - name: push docker image
  #       run: docker push ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/docker/${{ env.APP_NAME }}:${{ github.event.release.tag_name }}

  helm:
    # create, push and deploy helm chart
    runs-on: ubuntu-latest
    needs: [vars]
    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v1
        with:
          version: ${{ env.VERSION }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: authenticate to registry
        run: gcloud container clusters get-credentials ${{ env.GCP_CLUSTER_NAME }} --zone=${{ env.GCP_CLUSTER_ZONE }}
        shell: bash

      - name: kubeconfig
        run: kubectl config view
        shell: bash

      - name: bump version
        run: |
          sed -i 's/0.0.1/${{ env.VERSION }}/' helm/${{ env.APP_NAME }}/Chart.yaml
        shell: bash
        
      - name: save chart
        run: helm chart save helm/${{ env.APP_NAME }} ${{ needs.vars.outputs.HELM_IMAGE_TAG }}
        shell: bash
    
      - name: list charts
        run: helm chart list
        shell: bash

      - name: push helm chart
        run: helm chart push ${{ needs.vars.outputs.HELM_IMAGE_TAG }}
        shell: bash
